apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-models
  namespace: loan-prediction
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  AWS_DEFAULT_REGION: eu-west-1
  AWS_S3_ENDPOINT: http://minio.minio.svc.cluster.local:9000
  AWS_S3_BUCKET: models